language: python
sudo: false

before_install:
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
    texlive-latex-extra texlive-fonts-extra texlive-humanities texlive-science latex-xcolor
    dvipng texlive-latex-recommended python-pygments lmodern texlive-xetex
    latexdiff texlive-generic-recommended latexmk

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=3.5 pip mpmath matplotlib pytest pyflakes numpy scipy pyne gcc jinja2 gmpy2 cython scikit-umfpack colorama
  - source activate test-environment
  # Change to git+git://github.com/sympy/sympy.git when
  # https://github.com/sympy/sympy/pull/12088 is merged.
  - pip install git+git://github.com/asmeurer/sympy.git@Float-prec-fix

  - python -m transmutagen.gensolve --py-solve
  - cd py_solve
  - python setup.py build_ext --inplace
  - cd ..

  # Make matplotlib stuff work
  - export MATPLOTLIBRC=~/matplotlibrc
  - mkdir -p $MATPLOTLIBRC
  - >
    echo "backend : Agg" >> $MATPLOTLIBRC/matplotlibrc

script:
  - set -e
  - pyflakes transmutagen py_solve setup.py
  - PYTHONPATH=py_solve py.test transmutagen

  # Test the analysis scripts (except ORIGEN, since we need data for that)
  - PYTHONPATH=py_solve python -m transmutagen.analysis --nofission --file test.pgf
  - PYTHONPATH=py_solve python -m transmutagen.analysis --eigenvals --file test.pdf
  - PYTHONPATH=py_solve python -m transmutagen.analysis --pusa-coeffs --latex test.tex --file test.pgf
  - python -m transmutagen.analysis --gensolve --pairs-per-pass 3000

  # See if it installs
  - python setup.py sdist
  - pip install dist/*
  - cd /
  - python -c 'import transmutagen'
