#
# Super simple example of a Dockerfile
#
FROM ergs/ergs-base

WORKDIR /home

COPY ORIGEN.zip /home/ORIGEN.zip

RUN apt-get update && apt-get install -y unzip libc6-i386
RUN apt-get -y clean

RUN unzip /home/ORIGEN.zip

RUN tar -xf /home/C371ALLCP03/C371ALLCP.03/CCC371.03/c371tar3.gz

COPY decay.lib.patch decay.lib.patch
RUN patch -u origen22/libs/decay.lib -i decay.lib.patch

RUN conda install -y numpy scipy sympy matplotlib pyne mpmath
RUN conda remove -y sympy
RUN conda clean --all

RUN git clone https://github.com/sympy/sympy
ENV PYTHONPATH=/home/sympy

RUN git clone https://github.com/ergs/transmutagen.git
