#
# Super simple example of a Dockerfile
#
FROM ergs/ergs-base

WORKDIR /home

COPY ORIGEN.zip /home/ORIGEN.zip

RUN apt-get update && apt-get install -y unzip glibc-devel
RUN apt-get -y clean

RUN unzip /home/ORIGEN.zip

RUN tar -xf /home/C371ALLCP03/C371ALLCP.03/CCC371.03/c371tar3.gz

COPY decay.lib.patch decay.lib.patch
RUN patch -u origen22/libs/decay.lib -i decay.lib.patch

RUN conda install -y numpy scipy sympy matplotlib pyne mpmath xonsh gcc scikit-umfpack jinja2 gmpy2
RUN conda remove -y sympy
RUN conda clean --all

ADD o2prec /home/o2prec
RUN cd o2prec && ./make.xsh

RUN git clone https://github.com/sympy/sympy
ENV PYTHONPATH=/home/sympy
ENV LD_LIBRARY_PATH=/opt/conda/lib

RUN git clone https://github.com/ergs/transmutagen.git

# Checkout https://github.com/sympy/sympy/pull/12088. Remove when it is merged.
RUN cd sympy && git remote add asmeurer https://github.com/asmeurer/sympy
RUN cd sympy && git fetch asmeurer
RUN cd sympy && git checkout -t asmeurer/Float-prec-fix

RUN cd transmutagen && python -m transmutagen.gensolve --py-solve
RUN cd transmutagen/py_solve && python setup.py build_ext --inplace
