#
# Super simple example of a Dockerfile
#
FROM ergs/ergs-base

WORKDIR /home

COPY ORIGEN.zip /home/ORIGEN.zip

RUN apt-get update && apt-get install -y unzip libc6-i386 libc6 linux-headers-amd64
RUN apt-get -y clean

RUN unzip /home/ORIGEN.zip

RUN tar -xf /home/C371ALLCP03/C371ALLCP.03/CCC371.03/c371tar3.gz

COPY decay.lib.patch decay.lib.patch
RUN patch -u origen22/libs/decay.lib -i decay.lib.patch

RUN conda install -y numpy scipy sympy matplotlib pyne mpmath xonsh gcc scikit-umfpack jinja2 gmpy2
RUN conda clean --all

ENV LD_LIBRARY_PATH=/opt/conda/lib

RUN git clone https://github.com/ergs/transmutagen.git

RUN cd transmutagen && python -m transmutagen.gensolve --py-solve --json transmutagen/data/gensolve_origen_alpha_as_He4.json
RUN cd transmutagen/py_solve && python setup.py build_ext --inplace
